pull_request_rules:
  - name: VM2-PRIVATE-POST-DOWNGRADE-CANARY
    conditions:
      - label = VM2-NEVER-PRIVATE-DOWNGRADE
    actions:
      comment:
        message: VM2-PRIVATE-POST-DOWNGRADE-CONTENT
